created js for mobile_menu
Created markup for mobile menu
Created js for mobile menu
Facing compilation issue due to _common.scss:

Compilation Error
Error: File "/Users/oreshnyk/Desktop/donut-masterclass/src/sass/~node_modules/modern-normalize/modern-normalize.css" not found
        on line 1 of Users/oreshnyk/Desktop/donut-masterclass/src/sass/_common.scss
        from line 1 of sass/Users/oreshnyk/Desktop/donut-masterclass/src/sass/index.scss
>> @import '~node_modules/modern-normalize/modern-normalize.css';